### ISSUE TITLE
Thing to note.

### ISSUE THREAD

**Issue by htkcodes** [0xV19/TokenProvidence#1]
This won't work for you unless you've approved the token before hand.

**Comment by 0xV19** [comment]
Good catch, I forgot to add the ```approve``` call after the buy in both ```checkInternalFee``` and ```tokenToleranceCheck```. It works with that.

**Comment by htkcodes** [comment]
fixed - 2b40be1a1db3bd92809bf3fa114edac891990ad2

**Comment by 0xV19** [comment]
thanks
